version: '3.8'

services:
  mooc-api:
    build: .
    environment:
      MOOC_HOST: 0.0.0.0
      MOOC_DBHOST: mysql
      MOOC_DBUSER: admin
      MOOC_DBPASS: admin
      MOOC_DBPORT: 3306
      MOOC_DBNAME: gourse_api_db
    ports:
      - 8080:8080

  mysql:
    image: mysql:8.0.22
    volumes:
      - mysql_data:/var/lib/mysql
      - ./sql:/docker-entrypoint-initdb.d
    environment:
      MYSQL_DATABASE: gourse_api_db
      MYSQL_USER: admin
      MYSQL_PASSWORD: admin
      MYSQL_ROOT_PASSWORD: admin

volumes:
  mysql_data: